name: sriov-e2e-test
run-name: sriov-e2e-test initiated by ${{ github.actor }}
on:
  pull_request:
    types: [labeled]
    inputs:
      nic_series:
        description: 'NIC hardware'
        default: '810'
  workflow_dispatch:
    inputs:
      nic_series:
        description: 'NIC hardware'
        required: true
        default: '810'
        type: choice
        options:
        - 810
        - 710
jobs:
  e2e-tests:
    runs-on: [self-hosted, 810]
    if: |
      ${{ contains(github.event.label.name, 'e2e-test') ||
        github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f sriov/requirements.txt ]; then pip install -r sriov/requirements.txt; fi
          pip install mock
      - name: e2e test
        working-directory: ${{ github.workspace }}
        run: |
          files=`git diff --name-only origin/main`
          echo "diff files: $files"
          pyfiles="conftest.py config.py configtestdata.py utils.py exec.py macros.py"
          mode=""
          tests=()
          for f in ${files}; do
            file=$(basename $f)
            if [[ " ${pyfiles} " =~ " ${file} " ]]; then
              mode="full"
              break
            elif [[ "$f" =~ "sriov/tests/" ]]; then
              parentdir=$(dirname "$f")
              testname=$(basename "${parentdir}")
              tests+=("${testname}")
            fi
          done
          cd sriov/tests
          cp /config/*.yaml ./
          if [[ "${mode}" == "full" ]]; then
            pytest -v --html=report.html --self-contained-html common
            echo "generated=true" >> $GITHUB_ENV
          elif [[ ${#tests[@]} -ne 0 ]]; then
            test_string="pytest -v --html=report.html --self-contained-html"
            for testname in $(echo "${tests[@]}" | tr ' ' '\n' | sort -u); do
              test_string="${test_string} ${testname}"
              echo "Testing ${testname}"
            done
            ${test_string}
            echo "generated=true" >> $GITHUB_ENV
          else
            echo "no common code or test case code change - no e2e run"
            echo "generated=false" >> $GITHUB_ENV
          fi
      - name: Upload HTML Artifact
        if: ${{ env.generated == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: sriov/tests/report.html
          retention-days: 3
      - name: Display Status
        run: echo "This job's status is ${{ job.status }}."
    env:
      NIC: ${{ inputs.nic_series }}
  remove-label:
    needs: e2e-tests
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    if: always() && contains(github.event.label.name, 'e2e-test')
    steps:
      - name: remove label
        run: |
          curl --silent -X DELETE -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ github.token }}' 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/e2e-test'
